apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  name: snapshot
  namespace: default
spec:
  application: app
  images:
    - component: component1
      pullSpec: pullspec1
    - component: component2
      pullSpec: pullspec2
    - component: component3
      pullSpec: pullspec3
