apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlan
metadata:
  name: default
  namespace: default
spec:
  displayName: Users's ReleasePlan
  application: app
  target:
    namespace: managed
    workspace: root:users:someuser:managed
