resources:
# All RBAC will be applied under this service account in
# the deployment namespace. You may comment out this resource
# if your manager will use a service account that exists at
# runtime. Be sure to update RoleBinding and ClusterRoleBinding
# subjects if changing service account names.
- service_account.yaml
- role.yaml
- role_binding.yaml
- leader_election_role.yaml
- leader_election_role_binding.yaml
# Aggregating roles which are otherwise done by OLM
- application_role.yaml
- application_role_binding.yaml
- environment_viewer_role.yaml
- environment_role_binding.yaml
- release_editor_role.yaml
- release_role_binding.yaml
- release_viewer_role.yaml
- releaseplanadmission_editor_role.yaml
- releaseplanadmission_role_binding.yaml
- releaseplanadmission_viewer_role.yaml
- releaseplan_editor_role.yaml
- releaseplan_role_binding.yaml
- releaseplan_viewer_role.yaml
- snapshotenvironmentbinding_editor_role.yaml
- snapshotenvironmentbinding_role_binding.yaml
- snapshot_editor_role.yaml
- snapshot_role_binding.yaml
- snapshot_viewer_role.yaml
# Tekton
- tekton_role.yaml
- tekton_role_binding.yaml
# Application service
- component_role.yaml
- component_role_binding.yaml
# Prometheus
- prometheus_service_account.yaml
- prometheus_viewer_role.yaml
- prometheus_role_binding.yaml
# The following RBAC configurations are used to protect
# the metrics endpoint with authn/authz. These configurations
# ensure that only authorized users and service accounts
# can access the metrics endpoint. Comment the following
# permissions if you want to disable this protection.
# More info: https://book.kubebuilder.io/reference/metrics.html
- metrics_auth_role.yaml
- metrics_auth_role_binding.yaml
- metrics_reader_role.yaml
