# permissions for end users to view releasestrategies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: releasestrategy-viewer-role
rules:
- apiGroups:
  - appstudio.redhat.com
  resources:
  - releasestrategies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - appstudio.redhat.com
  resources:
  - releasestrategies/status
  verbs:
  - get
