apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kcp-syncer-jbieren-quicklabs-s46oqxua
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - "create"
  - "list"
  - "watch"
- apiGroups:
  - "apiextensions.k8s.io"
  resources:
  - customresourcedefinitions
  verbs:
  - "get"
  - "watch"
  - "list"
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  - serviceaccounts
  verbs:
  - "*"
- apiGroups:
  - "apps"
  resources:
  - deployments
  verbs:
  - "*"
## Add the following to allow the synctarget to become ready.
## This does not seem to have any effect on the CRDs becoming
## available or permissions accessing them in KCP, however.
- apiGroups:
  - "tekton.dev"
  resources:
  - pipeineruns
  verbs:
  - "*"
- apiGroups:
  - "appstudio.redhat.com"
  resources:
  - snapshots
  - releases
  - releaseplans
  - releaseplanadmissions
  - releasestrategies
  verbs:
  - "*"
