bases:
- ../manager
- ../rbac

patches:
# Add APIExport flag to the operator arguments list
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --api-export-name=release-service
  target:
    kind: Deployment
    name: controller-manager
# Disable webhooks by default on KCP
# Webhooks can be optionally enabled after deploy
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: ENABLE_WEBHOOKS
        value: "false"
  target:
    kind: Deployment
    name: controller-manager

resources:
  - apiexport_release.yaml
  - apiresourceschema_release.yaml
