kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: grafana-operator-system

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  # release-release-attempts
  #    ^            ^
  #    |            |
  #  service      panel
  - name: grafana-dashboard-release-release-attempts
    files:
      - grafana-dashboards/release-attempts.json

resources:
  - prometheus/monitor.yaml
